// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import DisableBtnController from "./disable_btn_controller"
application.register("disable-btn", DisableBtnController)

import ForumSubscriptionController from "./forum_subscription_controller"
application.register("forum-subscription", ForumSubscriptionController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import MapController from "./map_controller"
application.register("map", MapController)

import ViewToggleController from "./view_toggle_controller"
application.register("view-toggle", ViewToggleController)
